### ISSUE TITLE
--fixperm option should not create directories

### ISSUE THREAD

**Issue by ro-ket** [claudiofahey/isilon-hadoop-tools#17]
The description of --fixperm is that it will "fix permissions and owners on existing directories". 

As currently written, the option actually does this: create a directory if it doesn't exist; and fix permissions if it does exist.

I believe the correct thing to do is have it **only** fix permissions.

Separately, perhaps another option is needed to only create (and set permissions on) missing directories.

**Comment by ghost** [comment]
So here is what I see

Fix perm is optional.  Default is "N"

Normally then if the dirs do not exist makedir is called to make the dirs, as root with no other perms specified.  Fixperm is then called to alter them.

If dirs do exist, then you have three additional cases.
1.  fixperm was yes..in which case fixperm is called 
2.  Fixperm has nested check for posix and if called aces are removed then perms fixed
3.  Or directories did exist, fixperm wasn't called..in which case it says directory exists but no fixperm specified.

Fixperm does not appear to create directories?  If we agree I will close?

**Comment by ghost** [comment]
Closing after discussion with RoKet.  The scripts will fix permissions according to the users and directories created by these scripts.  If the user environment has different users entirely, or does not have all of the users, the scripts will throw errors around the fixing of permissions in the case a user does not exist.  It is not quite an easy button to deal with all permissions related errata; especially in concert with the posix-only flag in an environment making use of multiprotocol.  This verbiage change only exists in the new repo.  (github.com/isilon/isilon_hadoop_tools.  )
