### ISSUE TITLE
Script needs to purge extended ACLs

### ISSUE THREAD

**Issue by ro-ket** [claudiofahey/isilon-hadoop-tools#18]
The script needs to either **always** revert to POSIX permissions, or **optionally** allow for permissions to be reverted to POSIX permissions.

The  fixperm function (invoked in normal directory creation and in the `--fixperm` script option) assumes that only POSIX permissions exist on the directories. If there are other modes on directories (aka extended ACLs), they will not be removed.

The script needs to allow removal of all modes.

I see two ways to do this. Which to implement depends on whether we decide that we require all to be completely removed, or if we only recommend all to be removed:
1. If we required, simply add a `chmod -D $1` before [line 69](https://github.com/claudiofahey/isilon-hadoop-tools/blob/4176799934527adec0f25cc034eaf293e7783e1b/onefs/isilon_create_directories.sh#L69) within the `fixperm` function.  Do this before `chmod $4 $1`:
   
   > ```
   >   chmod -D $1
   >   chmod $4 $1
   > ```
2. If we recommend, add a new option for the script which allows admins to revert these directories to POSIX. The `chmod -D $1 in the fixperm function.
   - Default to "no" around line 15:
     
     > POSIX="n"
   - Add command line near line 120:
     
     > ```
     >  "--posix-only")
     >         echo "Info: will remove all existing permissions, including mode equivalent of extended ACLs, before setting POSIX permissions."
     >         POSIX="y"
     >         ;;
     > ```
   - Only run `chmod -D` when this flag is set. Do this before `chmod $4 $1`:
     
     > ```
     >   if [ "POSIX" == "y" ] ; then
     >     chmod -D $1
     >   chmod $4 $1
     > ```

**Comment by ghost** [comment]
Closed with your commit to the new repo July 11.
