### ISSUE TITLE
Undo creation of cdh users and directories

### ISSUE THREAD

**Issue by tatefer** [claudiofahey/isilon-hadoop-tools#7]
Hi Claudio.

I ran both the "isilon_create_users.sh" and "isilon_create_directories.sh" scripts with the "cdh" option.
But I'm having some problems installing the Cloudera distribution in my hadoop cluster.

For that reason, I have decided to install Hortonwoks instead of Cloudera, and I have executed the above scripts in Isilon with the "hwx" option, but, as expected, many errors appeared when creating the users (see below).

What should I do in order to be able to run the scripts succesfully? That is, which actions should I perform, as for instance, delete users, delete groups, to be able to run the scripts with the "hwx" option?

Do you have any "undo script" to perfom these actions?

---
## Errors

IsilonSimulatorLab-1# bash /ifs/IsilonSimulatorLab/scripts/isilon-hadoop-tools/onefs/isilon_create_users.sh --dist hwx --startgid 501 --startuid 501 --zone System

Info: Hadoop distribution:  hwx
Info: groups will start at GID 501
Info: users will start at UID 501
Info: will put users in zone:  System
Info: HDFS root:  /ifs/IsilonSimulatorLab/System/hadoop
Failed to create persona 'GROUP:ranger'
Failed to create persona 'GROUP:kms'
Failed to create persona 'GROUP:atlas'
Failed to create persona 'GROUP:ams'
Failed to add member UID:501 to group GROUP:hadoop: User is already in local group
Failed to add member UID:502 to group GROUP:hadoop: User is already in local group
Failed to add member UID:503 to group GROUP:hadoop: User is already in local group
Failed to create persona 'USER:storm'
Failed to create persona 'USER:falcon'
ERRORS FOUND:
-  ERROR:  Group hdfs already exists at gid 501 in zone System
-  ERROR:  Group mapred already exists at gid 502 in zone System
-  ERROR:  Group yarn already exists at gid 503 in zone System
-  ERROR:  Group hbase already exists at gid 505 in zone System
-  ERROR:  GID 506 already in use by group hive in zone System
-  ERROR:  GID 507 already in use by group hue in zone System
-  ERROR:  GID 508 already in use by group impala in zone System
-  ERROR:  Group hive already exists at gid 506 in zone System
-  ERROR:  GID 507 already in use by group hue in zone System
-  ERROR:  Group oozie already exists at gid 509 in zone System
-  ERROR:  GID 510 already in use by group sample in zone System
-  ERROR:  GID 511 already in use by group solr in zone System
-  ERROR:  Group flume already exists at gid 504 in zone System
-  ERROR:  Group hue already exists at gid 507 in zone System
-  ERROR:  GID 508 already in use by group impala in zone System
-  ERROR:  GID 509 already in use by group oozie in zone System
-  ERROR:  Group sqoop already exists at gid 516 in zone System
-  ERROR:  Group spark already exists at gid 512 in zone System
-  ERROR:  GID 513 already in use by group sqoop2 in zone System
-  ERROR:  GID 514 already in use by group hadoop in zone System
-  ERROR:  GID 515 already in use by group supergroup in zone System
-  ERROR:  GID 516 already in use by group sqoop in zone System
-  ERROR:  GID 517 already in use by group anonymous in zone System
-  ERROR:  Group hadoop already exists at gid 514 in zone System
-  ERROR:  User hdfs already exists at uid 501 in zone System
-  ERROR:  User mapred already exists at uid 502 in zone System
-  ERROR:  User yarn already exists at uid 503 in zone System
-  ERROR:  User hbase already exists at uid 505 in zone System
-  ERROR:  UID 506 already in use by user hive in zone System
-  ERROR:  UID 507 already in use by user hue in zone System
-  ERROR:  UID 508 already in use by user impala in zone System
-  ERROR:  User hive already exists at uid 506 in zone System
-  ERROR:  UID 507 already in use by user hue in zone System
-  ERROR:  User oozie already exists at uid 509 in zone System
-  ERROR:  UID 510 already in use by user sample in zone System
-  ERROR:  UID 511 already in use by user solr in zone System
-  ERROR:  User flume already exists at uid 504 in zone System
-  ERROR:  User hue already exists at uid 507 in zone System
-  ERROR:  UID 508 already in use by user impala in zone System
-  ERROR:  UID 509 already in use by user oozie in zone System
-  ERROR:  UID 510 already in use by user sample in zone System
-  ERROR:  UID 511 already in use by user solr in zone System
-  ERROR:  User spark already exists at uid 512 in zone System
-  ERROR:  UID 513 already in use by user sqoop2 in zone System
-  ERROR:  Could not create user ranger with uid 514 in zone System
-  ERROR:  Could not create user kms with uid 515 in zone System
-  ERROR:  Could not create user atlas with uid 516 in zone System
-  ERROR:  Could not create user ams with uid 517 in zone System
-  ERROR:  Could not add user hdfs to hadoop group in zone System
-  ERROR:  Could not add user mapred to hadoop group in zone System
-  ERROR:  Could not add user yarn to hadoop group in zone System
-  ERROR:  Could not add user storm to hadoop group in zone System
-  ERROR:  Could not add user falcon to hadoop group in zone System

Many thanks.
Regards. Fernando.

**Comment by ghost** [comment]
There is not an undo flag to remove the users, groups, and directories created.  To prepare the environment so it can be run again, first remove the groups in the file provider for this access zone associated with hadoop.  Then do the same for the users.  There is a case statement in the script for groups and users created for each distribution so you know which ones need removal.  You can accomplish user and group removal either in the gui or using the isi auth command.  Once they are removed you'll probably want to remove the directories that were created as well.  Each distribution tends to have different user assignments, group assignments, and slightly different directory layout as well.

**Comment by ghost** [comment]
Correction, first remove the groups in the local provider for this access zone associated with hadoop.

**Comment by tatefer** [comment]
Ok, many thanks for the info. I'll try it!!

**Comment by ghost** [comment]
Fernando was that sufficient to help you resolve the matter?

**Comment by tatefer** [comment]
Oh, yes. I had some problems at the beginning but after two or three tries I finally made it.
Many thanks.
Fernando.

**Comment by ghost** [comment]
We've kicked around the idea of deletion functions several times.  At the end of the day we work for a storage company and we don't like deleting your stuff.  You can see where if somebody ran that, without knowing what it did, especially if that was the directories script, super bad things could happen.

**Comment by ghost** [comment]
closing issue
