### ISSUE TITLE
HBase Master and Region Servers will not start after HDP 2.3.4 installation

### ISSUE THREAD

**Issue by JeffreyGroves** [claudiofahey/isilon-hadoop-tools#8]
Our customer reported the following issue with the tools when installing HDP 2.3.4 and Ambari 2.1.2.1 using the tools provided here.  The customer reported:

> "One of the tools provided at the github destination mentioned in that document is a create directories shell script. This script takes in various parameters, including which Hadoop distribution you are using. Based on that parameter, the script pre-creates various hdfs directories on the Isilon. If Hortonworks is specified as the distro, the pre-created directories do not including anything under /apps/hbase. However, I did notice that for one of the other distributions, phd, it does pre-create /apps/hbase/staging and sets its permissions to 711. Based on that, we changed our permissions on that directory, and were able to start HBase. "

Please take a look and address as required.

Thank you,

Jeff Groves
Hortonwork Support

**Comment by ghost** [comment]
Thanks, been meaning to give feedback.  Lots of travel.  There are a number of modifications I'm consolidating and this will be merged and pushed by the end of the week to include your proposed changes.

**Comment by ghost** [comment]
Fix posted in 0.67
